services:
  - type: web
    name: movement_records
    env: ruby
    plan: starter
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: movement_records_db
          property: connectionString
databases:
  - name: movement_records_db
    plan: starter