# SQLite settings for development & test
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

# Production database settings (MySQL)
production:
  adapter: mysql2
  encoding: utf8
  database: movement_records_production
  username: rails
  password: "yourpassword"
  host: localhost
  pool: 5

cable:
  adapter: redis
  url: redis://localhost:6379/1
